### PR TITLE
drm/i915/bxt: Enable VBT based BL control for DP

### PR DESCRIPTION
**Pull request by yugang**
Currently, BXT_PP is hardcoded with value '0'.
It practically disabled eDP backlight on MRB (BXT) platform.

This patch will tell which BXT_PP registers (there are two set of
PP_CONTROL in the spec) to be used as defined in VBT (Video Bios Timing
table) and this will enabled eDP
backlight controller on MRB (BXT) platform.

Signed-off-by: Mustamin B Mustaffa <mustamin.b.mustaffa@intel.com>
Signed-off-by: Fan Yugang <yugang.fan@intel.com>
Change-Id: Ibdfea5c3b2ff1cfdda2d1313e0b6c506ec5b5e9b

### CODE REVIEW

**Comment by yugang** [comment]
this will fix the 4.14 eDP backlight off issue

**Comment by yugang** [comment]
@kalyankondapally , pls help review & thanks

**Comment by kalyankondapally** [comment]
@yugang Are you able to send this patch to i915 mailing list for review ? You will need to fix your commit message removing MRB terms and making it generic.

**Comment by yugang** [comment]
ok, fixed commit message.

**Comment by yugang** [comment]
@kalyankondapally, intel-gfx@lists.freedesktop.org? i haven't tried this, do you have some bkm to process the review? e.g. the maill need attach the patch file? ..., thanks

**Comment by kalyankondapally** [comment]
@yugang  Can you update your commit message  based on the template here: https://github.com/intel/kernel-i915-intel/wiki/Contributions

**Pull request closed without merging**
